backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"     # Carpeta en tu repo donde guardar imágenes
public_folder: "/images/uploads"   # Ruta pública para mostrar imágenes

collections:
  - name: "paginas"
    label: "Páginas"
    files:
      - file: "index.html"
        label: "Inicio"
        name: "inicio"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Contenido", name: "body", widget: "markdown" }

  - name: "blog"
    label: "Entradas del Blog"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Contenido", name: "body", widget: "markdown" }
